package com.example.arweld.core.drawing2d.validation

/**
 * Stable violation codes for Drawing2D validation v1.
 */
object CodesV1 {
    const val SCHEMA_VERSION_MISMATCH = "SCHEMA_VERSION_MISMATCH"
    const val DRAWING_ID_BLANK = "DRAWING_ID_BLANK"
    const val REV_NEGATIVE = "REV_NEGATIVE"
    const val PAGE_WIDTH_INVALID = "PAGE_WIDTH_INVALID"
    const val PAGE_HEIGHT_INVALID = "PAGE_HEIGHT_INVALID"

    const val LAYERS_EMPTY = "LAYERS_EMPTY"
    const val LAYER_ID_DUPLICATE = "LAYER_ID_DUPLICATE"
    const val LAYER_ORDER_DUPLICATE = "LAYER_ORDER_DUPLICATE"
    const val LAYER_ORDER_NEGATIVE = "LAYER_ORDER_NEGATIVE"

    const val ENTITY_ID_DUPLICATE = "ENTITY_ID_DUPLICATE"
    const val ENTITY_LAYER_UNKNOWN = "ENTITY_LAYER_UNKNOWN"

    const val GROUP_MEMBER_UNKNOWN = "GROUP_MEMBER_UNKNOWN"
    const val TAG_TARGET_UNKNOWN = "TAG_TARGET_UNKNOWN"

    const val ATTACHMENT_PATH_INVALID = "ATTACHMENT_PATH_INVALID"
    const val ATTACHMENT_SHA256_INVALID = "ATTACHMENT_SHA256_INVALID"

    const val PATCH_SCHEMA_VERSION_MISMATCH = "PATCH_SCHEMA_VERSION_MISMATCH"
    const val PATCH_DRAWING_ID_MISMATCH = "PATCH_DRAWING_ID_MISMATCH"
    const val PATCH_BASE_REV_INVALID = "PATCH_BASE_REV_INVALID"
}
